#Reusable  workflow
name: Reusable-workflow
on: workflow_call
    
#CI/CD job w        
jobs:
  build:
    runs-on: ubuntu-latest
      steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      ##- name: composite action
        ##uses: ./.github/workflows
      - name: create data
        run: |
            printf '{
              "data_1": "Text data",
              "data_2": true
              }' >> testartifact.json
      - uses: actions/upload-artifact@v3
        with:
          name: testartifact.json
          path: ./

              
              
      
       
 #Download artifact 
  Deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: development 
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: testartifact.json
          path: main
      - name: Build project
        run: echo "Build project"
      - name: Deploy
        run: echo "Deploying.."
  test:
    needs: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Test the build
        run: |
          ls -la ${{ github.workspace }}
